### ISSUE TITLE
Consider switching to lowercase types

### ISSUE THREAD

**Issue by mrchief** [kevin940726/emoji-cz#2]
Currently this package uses Titlecase types (**F**eat, **D**ocs etc). Tools like semantic-release rely on all lowercase types to generate releases. 

Consider switching to all lowercase types (feat, docs and so on) so that it works better with other tools. 

Maybe an option to switch to Titlecase (default lowercase and option to switch to Titlecase or vice versa) will also be good - although I guess its more work for not much benefit.

**Comment by kevin940726** [comment]
You can always rename the types using config file
```json
"emoji-cz": {
  "types": {
    "Fix": {
      "name": "fix"
    },
    "Feat": {
      "name": "feat"
    }
  }
}
```

... and so on. But I agree that it can be a good default if it break some popular tooling. PR welcome!

**Comment by mrchief** [comment]
I think this should do it. 

Also, I moved emoji to the end, because:

 - semantic release and such tools require an exact string match (emoji characters fail the test)
 - emoji message at the end is kinda less intrusive. But I'm OK if you wanna bring it to front of the subject like so: `[emoji] [subject]`
