### ISSUE TITLE
Can I translate your project in Korean?

### ISSUE THREAD

**Issue by devjiro76** [kevin940726/emoji-cz#4]
I translated your project to Korean version.
https://github.com/devjiro76/emoji-cz-kr

Sorry about I didn't ask you before fork.
Question is late but can I translate your project in Korean?
If you mind I'll delete this repo.

**Comment by kevin940726** [comment]
That's totally OK, the package is licensed under MIT, you can read the full license [here](https://github.com/kevin940726/emoji-cz/blob/master/LICENSE). Thanks for the appreciation.
